---
- name: easy_install pip
  become: True
  easy_install:
    name: pip
    state: latest

- name: Ensure path for pip --user
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: export PATH="$HOME/Library/Python/2.7/bin:$PATH"' >> "$HOME/.bash_profile
