---
- name: Check if pip installed
  stat: 
    path: /usr/local/bin/pip2
  register: pip2_stat
  ignore_errors: True

- name: easy_install pip
  become: True
  easy_install:
    name: pip
    state: latest
  when: not pip2_stat.stat.exists


- name: Ensure path for pip --user
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: export PATH="$HOME/Library/Python/2.7/bin:$PATH"

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    extra_args: --user
    executable: /usr/local/bin/pip2
  with_items: "{{ pip_install_packages }}"
